/***************************************************************
* Name: Aidan Sharpe
* Course: Computer Science & Programming
* Class: CS04103 Section: 6
* Assignment Date: 9/22/2021
* File Name: Homework1-1ASharpe.cpp
*****************************************************************
* ID: Homework 1 Problem 1
* Purpose: Estimate the revenue generated by a specific division of a corporation.
*****************************************************************/

#include <iostream>
#include <string>
#include <iomanip>

using namespace std;

int main()
{
    const float PERCENT_TOTAL_SALES = .58;
    const int SALES = 86000000;

    float divisionRevenue = PERCENT_TOTAL_SALES * SALES;   // calculate the revenue estimate for the east coast division

    cout << fixed << setprecision(2) << "The East Coast Division generated $" << divisionRevenue << " in sales";

    return 0;
}
